version: '3.1'
services:
 node-app:
  restart: always
  user: root
  build: .
  image: harishsaravanakumar/finalflaskapp
  ports:
   - "8080:8080"
  secrets:
   - secretfile

secrets:
 secretfile:
  file: secretfile.yml
